import { Dat, Obj } from "../libs/Dat";
import { DateTime } from 'luxon';

export default (parsed: { file: string, dat: Dat }[]) =>
  `this file generated by \`npm run listing\` command.

generated at ${DateTime.now().toLocaleString(DateTime.DATETIME_FULL)}.

# Addons

${parsed.map(parseDat).join('\n')}

`;

const parseDat = ({ file, dat }: { file: string, dat: Dat }): string =>
  `## \`${file}\`

|name|obj|waytype|system_type|
|---|---|---|---|
${dat.objs.map(parseObj).join('\n')}
`;

const parseObj = (obj: Obj): string =>
  `|${obj.findParam('name')?.value}|${obj.findParam('obj')?.value}|${obj.findParam('waytype')?.value || 'N/A'}|${obj.findParam('system_type')?.value || 'N/A'}|`;
