import { DateTime } from 'luxon';
import { parsedObj } from "../interface";

export default (parsed: { file: string, objs: parsedObj[] }[]) =>
  `this file generated by \`npm run listing\` command.

generated at ${DateTime.now().toLocaleString(DateTime.DATETIME_FULL)}.

# Addons

${parsed.map(parseDat).join('\n')}

`;

const parseDat = ({ file, objs }: { file: string, objs: parsedObj[] }): string =>
  `## \`${file}\`

|name|translate|obj|waytype|system_type|
|---|---|---|---|---|
${objs.map(parseObj).join('\n')}
`;

const parseObj = (obj: parsedObj): string =>
  `|${obj.name}|${obj.translates.join('<br>')}|${obj.obj}|${obj.waytype}|${obj.system_type}|`;
