name: CI

on:
  push:
    branches: [master, develop]
    tags: ["**"]
  pull_request:
    branches: [master]
jobs:
  pak-test:
    runs-on: ubuntu-latest
    steps:
      - name: install makeobj via apt
        run: sudo apt install -y simutrans-makeobj

      - name: Checkout
        uses: actions/checkout@v2

      - name: copy env
        run: cp .env.ci .env

      - name: make pak files
        run: npm ci && npm run build

      - name: show error log
        if: failure()
        run: cat /home/runner/.npm/_logs/*.log

  release:
    needs: pak-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: install makeobj via apt
        run: sudo apt install -y simutrans-makeobj

      - name: Checkout
        uses: actions/checkout@v2

      - name: copy env
        run: cp .env.ci .env

      - name: make pak files
        run: npm ci && npm run release

      - name: make release file
        run: cp -r ./extra/* ./release && cp ./docs/thumbnail.png ./release && cp LICENSE ./release && cp ./src/compat.tab ./release && zip -r release.zip ./release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ startsWith(github.ref, 'refs/tags/test') }}
          files: |
            release.zip
