name: Release

on:
  push:
    branches: [master]
    tags: ["**"]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install makeobj via apt
        run: sudo apt install -y simutrans-makeobj

      - name: Checkout
        uses: actions/checkout@v2

      - name: make pak files
        run: cd src && /usr/lib/simutrans/makeobj pak256

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: install makeobj via apt
        run: sudo apt install -y simutrans-makeobj

      - name: Checkout
        uses: actions/checkout@v2

      - name: make pak files
        run: cd src && /usr/lib/simutrans/makeobj pak256 && mv *.pak ../dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*
